# Generated by Django 3.2.7 on 2021-10-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=0, max_digits=5)),
                ('y', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
