# Generated by Django 3.2.7 on 2021-10-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haato', '0002_remove_miku_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='miku',
            name='y',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
