# Generated by Django 3.2.7 on 2021-10-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haato', '0003_miku_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miku',
            name='y',
        ),
    ]
