# Generated by Django 3.2.7 on 2021-10-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haato', '0005_miku_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miku',
            name='y',
        ),
    ]
