# Generated by Django 3.2.8 on 2022-06-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haato', '0007_auto_20220320_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='miku',
            name='y',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miku',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='miku',
            name='x',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
